[package]
name = "nu_plugin_unicode"
description = "A utility for working with Unicode text"

version = "0.1.0-alpha.1"
edition = "2024"

authors = ["Skyler Hawthorne <skyler@dead10ck.dev>"]

repository = "https://github.com/dead10ck/nu_plugin_unicode"
license = "MPL-2.0"
readme = "README.md"
keywords = ["nu", "nushell", "plugin", "unicode"]
categories = ["command-line-utilities"]

exclude = [ ".github/" ]

[package.metadata.release]
allow-branch = [ "main" ]
pre-release-hook = [ "./pre-release" ]

[[bin]]
name = "nu_plugin_unicode"
bench = false

[lib]
bench = false

[profile.release]
codegen-units = 1
lto = "thin"

[dependencies]
nu-plugin = "0.108.0"
nu-protocol = "0.108.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
ucd-parse = "0.1.13"

encoding_rs_io = "0.1.7"
encoding_rs = "0.8.35"
datafusion = "50.2.0"
dirs = "6.0.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread"]}
chrono = "0.4.42"
chrono-tz = "0.10.4"

[dev-dependencies]
nu-plugin-test-support = "0.108.0"
# nu-command = "0.108.0"
